/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BFormFile: typeof import('bootstrap-vue-next/components/BFormFile')['BFormFile']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    BPlaceholder: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholder']
    BPlaceholderCard: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholderCard']
    BPlaceholderWrapper: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholderWrapper']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    MainFrame: typeof import('./src/components/MainFrame.vue')['default']
    ModalMessage: typeof import('./src/components/ModalMessage.vue')['default']
    NavbarView: typeof import('./src/components/NavbarView.vue')['default']
    OffcanvasView: typeof import('./src/components/OffcanvasView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
